[package]
name = "weba-crypto-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
subtle = "2.5" # For constant-time comparisons
aes-gcm = "0.10"
x25519-dalek = { version = "2.0", features = ["getrandom", "static_secrets"] }
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
getrandom = { version = "0.2", features = ["js"] }
ml-kem = "0.2" # NIST Post-Quantum Cryptography (Kyber)
rand = { version = "0.8", features = ["small_rng"] }
sha2 = "0.10.9"
hkdf = "0.12.4"
ml-dsa = "0.0.4"
