import { describe, expect, test } from "bun:test";
import path from "path";

describe("Web/A CLI Verifier", () => {
    const TSA_HTML = path.resolve("tests/fixtures/tsa-dist/tsa.html");

    test("should verify a fully valid LTV container", () => {
        // Ensure the file exists (generated by ssg_tsa.test.ts)
        
        const proc = Bun.spawnSync(["bun", "run", "src/bin/weba-verify.ts", TSA_HTML, "--hmp", "--json"]);

        if (!proc.success) {
            console.log("CLI Stdout:", proc.stdout.toString());
            console.error("CLI Stderr:", proc.stderr.toString());
            throw new Error(`CLI failed with code ${proc.exitCode}`);
        }

        const outputStr = proc.stdout.toString();
        const output = JSON.parse(outputStr);
        
        expect(output.isValid).toBe(true);
        expect(output.l4.valid).toBe(true);
        expect(output.l3.valid).toBe(true);
        expect(output.l2.isValid).toBe(true);
        // l1 might be valid if structure blob is present.
        
        expect(output.tsa.valid).toBe(true);
        expect(output.tsa.timestamp).toBeDefined();
    });
});
