
import { type BunFile } from "bun";

async function build() {
    console.log("Building Web/A client bundle...");

    // 1. Build Bundle
    const buildProc = Bun.spawn(["bun", "build", "src/weba/client/index.ts", "--outfile", "src/weba/client/bundle.js"]);
    await buildProc.exited;

    if (buildProc.exitCode !== 0) {
        console.error("Build failed");
        process.exit(1);
    }

    // 2. Read Bundle
    const bundleFile = Bun.file("src/weba/client/bundle.js");
    const bundleContent = await bundleFile.text();

    // 3. Create Embed
    // Escape backticks and backslashes if necessary for template literal
    // Or just use JSON.stringify to be safe
    const escapedContent = JSON.stringify(bundleContent);

    const embedContent = `
// Auto-generated by scripts/build_weba_client.ts
export const CLIENT_BUNDLE = ${escapedContent};
`;

    // 4. Write Embed
    await Bun.write("src/weba/client/embed.ts", embedContent);
    console.log("Generated src/weba/client/embed.ts");
}

build();
