import { type BunFile } from "bun";

async function build() {
  console.log("Building Parquet bundle...");
  const buildProc = Bun.spawn([
    "bun",
    "build",
    "src/form/client/parquet_provider_bundle.ts",
    "--format=esm",
    "--outfile",
    "src/form/client/parquet_bundle.js",
  ]);
  await buildProc.exited;

  if (buildProc.exitCode !== 0) {
    console.error("Parquet bundle build failed");
    process.exit(1);
  }

  const bundleFile: BunFile = Bun.file("src/form/client/parquet_bundle.js");
  let bundleContent = await bundleFile.text();
  bundleContent = bundleContent.replaceAll("</script>", "<\\/script>");

  const escapedContent = JSON.stringify(bundleContent);
  const embedContent = `// Auto-generated by scripts/build_parquet_bundle.ts
export const PARQUET_BUNDLE = ${escapedContent};
`;

  await Bun.write("src/form/client/parquet_embed.ts", embedContent);
  console.log("Generated parquet_embed.ts");
}

build();
