import fs from "fs-extra";
import path from "node:path";

const ROOT = process.cwd();
const SOURCE_WASM = path.join(
  ROOT,
  "node_modules",
  "parquet-wasm",
  "esm",
  "parquet_wasm_bg.wasm",
);
const TARGET = path.join(ROOT, "src", "form", "client", "parquet_wasm_embed.ts");

async function run() {
  const exists = await fs.pathExists(SOURCE_WASM);
  if (!exists) {
    throw new Error("parquet-wasm not installed");
  }
  const wasm = await fs.readFile(SOURCE_WASM);
  const b64 = wasm.toString("base64");
  const content = `// Auto-generated by scripts/embed_parquet_wasm.ts
export const PARQUET_WASM_BASE64 = "${b64}";
`;
  await fs.writeFile(TARGET, content);
  console.log("Generated parquet_wasm_embed.ts");
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
