import { baseLayout } from './base.js';

export interface BlogItem {
    title: string;
    description?: string;
    date?: string;
    author?: string;
    path: string;
    layout: string;
    isSystem?: boolean;
    excerptHtml?: string;
    excerptText?: string;
}

export interface BlogData {
    title: string;
    description?: string;
    profileUrl?: string;
    featuredCount?: number;
}

export function blogLayout(data: BlogData, allPages: BlogItem[], fontCss: string, fontFamilies: string[], htmlContent: string, latestArticleContent?: string, latestArticleData?: any) {
    // Filter out index and system pages, showing only user articles
    let articles = allPages.filter(item =>
        item.layout === 'article' &&
        !item.isSystem &&
        item.path !== 'index.html'
    );

    let latestArticleHtml = '';

    if (latestArticleContent && latestArticleData) {
        // Remove the latest article from the list to avoid duplication
        articles = articles.filter(item => item.path !== latestArticleData.path);

        const d = latestArticleData;

        // Reconstruct the article view (similar to articleLayout but simplified for stream)
        // We reuse .weba-article class for consistent styling
        latestArticleHtml = `
        <article class="weba-article" style="margin-bottom: 5rem; padding-bottom: 3rem; border-bottom: 1px dashed var(--border-color);">
            <header>
                <h1><a href="${d.path}" style="text-decoration:none; color:inherit;">${d.title}</a></h1>
                <div class="article-meta">
                    ${d.date ? `<span><time datetime="${d.date}">${d.date}</time></span>` : ''}
                    ${d.author ? `<span>By ${d.author}</span>` : ''}
                    ${d.ai_generated ? `<span class="ai-badge" title="Content generated by AI (Antigravity)">🤖 AI Generated</span>` : ''}
                </div>
            </header>
            <div class="article-body">
                ${latestArticleContent}
            </div>
            
             <div class="article-footer" style="margin-top: 2rem; text-align: right;">
                <a href="${d.path}" style="font-weight: bold; color: var(--link-color);">Permalink →</a>
             </div>
        </article>
        `;
    }

    const remainingList = articles.map(item => `
        <li class="blog-list-item">
            <a href="${item.path}" class="blog-list-title">${item.title}</a>
            <div class="blog-list-meta">
                ${item.date ? `<span>${item.date}</span>` : ''}
                ${item.author ? `<span class="sep">/</span><span>${item.author}</span>` : ''}
                ${item.description ? `<span class="sep">/</span><span>${item.description}</span>` : ''}
            </div>
        </li>
    `).join('');

    const profileLink = data.profileUrl
        ? `<a href="${data.profileUrl}" class="blog-profile-link">Profile</a>`
        : '';

    const fullContent = `
        <div class="blog-container">
            <header class="blog-header">
                <h1>${data.title}</h1>
                <div class="blog-header-top">
                     ${data.description ? `<p class="blog-lead">${data.description}</p>` : ''}
                     ${profileLink ? `<div class="blog-profile">${profileLink}</div>` : ''}
                </div>
                ${htmlContent ? `<div class="blog-custom-content">${htmlContent}</div>` : ''}
            </header>

            ${latestArticleHtml}

            ${remainingList ? `<section class="blog-list"><h2>More Articles</h2><ul>${remainingList}</ul></section>` : ''}
        </div>

        <style>
            .blog-container {
                max-width: 800px; /* Reduced from 1000px to match article width feeling */
                margin: 0 auto;
                padding: 3rem 1.5rem;
            }
            .blog-header {
                text-align: center;
                margin-bottom: 4rem;
                display: flex;
                flex-direction: column;
                align-items: center;
            }
            .blog-header-top {
                display: flex;
                flex-direction: row;
                align-items: center;
                gap: 1.5rem;
                margin-bottom: 1rem;
                flex-wrap: wrap;
                justify-content: center;
            }
            .blog-lead {
                font-size: 1rem;
                color: var(--text-muted);
                margin: 0;
            }
            .blog-profile {
                margin: 0;
            }
            .blog-profile-link {
                display: inline-flex;
                align-items: center;
                gap: 0.4rem;
                padding: 0.3rem 0.8rem;
                border-radius: 999px;
                border: 1px solid var(--border-color);
                color: var(--text-color);
                font-weight: 500;
                text-decoration: none;
                background: var(--bg-color);
                font-size: 0.85rem;
            }
            .blog-profile-link:hover {
                border-color: var(--link-color);
                color: var(--link-color);
            }
            .blog-custom-content {
                margin: 1rem auto 2rem;
                max-width: 600px;
                line-height: 1.6;
                text-align: center;
                font-size: 0.95rem;
            }
            
            /* Reuse Article Styles */
            .weba-article header {
                 text-align: left;
                 margin-bottom: 2rem;
            }
            .weba-article h1 {
                font-size: 2rem;
                margin-top: 0;
                border: none;
                margin-bottom: 0.5rem;
            }
            .article-meta {
                font-size: 0.9rem;
                color: var(--text-muted);
                display: flex;
                gap: 1rem;
                align-items: center;
            }

            .blog-list h2 {
                text-align: left;
                margin-bottom: 1.5rem;
                font-size: 1.4rem;
                border-bottom: 2px solid var(--border-color);
                padding-bottom: 0.5rem;
            }
            .blog-list ul {
                list-style: none;
                padding: 0;
                margin: 0;
                display: flex;
                flex-direction: column;
                gap: 1.5rem;
            }
            .blog-list-item {
                padding-bottom: 1.25rem;
                border-bottom: 1px solid var(--border-color);
                text-align: left;
            }
            .blog-list-title {
                display: inline-block;
                font-size: 1.15rem;
                font-weight: 600;
                color: var(--heading-color);
                text-decoration: none;
                margin-bottom: 0.35rem;
            }
            .blog-list-title:hover {
                color: var(--link-color);
            }
            .blog-list-meta {
                font-size: 0.85rem;
                color: var(--text-muted);
                display: flex;
                gap: 0.5rem;
                align-items: center;
                flex-wrap: wrap;
            }
            .blog-list-meta .sep {
                opacity: 0.3;
            }

            @media (max-width: 768px) {
                .blog-header h1 { font-size: 2.25rem; }
            }
        </style>
    `;

    return baseLayout({
        title: data.title,
        content: fullContent,
        fontCss,
        fontFamilies
    });
}
